services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://minearchive_user:minearchive_pass@db:5432/minearchive_db?schema=public"
      NODE_ENV: production
    depends_on:
      - db
    restart: always

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: minearchive_user
      POSTGRES_PASSWORD: minearchive_pass
      POSTGRES_DB: minearchive_db
    ports:
      - "5432:5432"
    volumes:
      - minearchive_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  minearchive_db_data:
